In [67]:
import pandas as pd
import matplotlib.pyplot as plt

In [68]:
amazon = pd.read_excel('/Users/apple/Desktop/SemanticDataIntegration/Dataset/Dataset1_Amazon.xlsx')
goodreads = pd.read_csv('/Users/apple/Desktop/SemanticDataIntegration/Dataset/Dataset2_GoodReads.csv')
kindle = pd.read_csv('/Users/apple/Desktop/SemanticDataIntegration/Dataset/Dataset3_Kindle.csv')
mediated_df = pd.read_csv('/Users/apple/Desktop/SemanticDataIntegration/Dataset/mediated_schema.csv', low_memory = False)

In [69]:
print(mediated_df.columns.tolist())

['title', 'author', 'rating', 'review_count', 'price', 'publication_year']

In [70]:
print(amazon.columns.tolist())

['Unnamed: 0', 'price', 'ranks', 'title', 'no_of_reviews', 'ratings', 'author', 'cover_type', 'year', 'genre']

In [71]:
print(goodreads.columns.tolist())

['source_URL', 'Readers Choice Votes', 'Readers Choice Category', 'Title', 'Author', 'Total Avg Rating', 'Number of Ratings', 'Number of Reviews', 'Number of Pages', 'Edition', 'Book Description', 'First Published date', 'Kindle Version and Price', 'Kindle Price', 'About the Author']

In [72]:
print(kindle.columns.tolist())

['asin', 'title', 'author', 'soldBy', 'imgUrl', 'productURL', 'stars', 'reviews', 'price', 'isKindleUnlimited', 'category_id', 'isBestSeller', 'isEditorsPick', 'isGoodReadsChoice', 'publishedDate', 'category_name']

In [73]:
#String matching using FUZZY WUZZY

In [74]:
#String based matching using JARO - WINKLER (tbd)

In [75]:
!pip install jellyfish

Requirement already satisfied: jellyfish in /opt/anaconda3/lib/python3.12/site-packages (1.0.1)

In [76]:
import jellyfish
import pandas as pd

# Mediated schema columns
mediated_cols = ['title', 'author', 'rating', 'review_count', 'price', 'publication_year']

# Columns of source datasets
amazon_cols = ['Unnamed: 0', 'price', 'ranks', 'title', 'no_of_reviews', 'ratings', 'author', 'cover_type', 'year', 'genre']
goodreads_cols = ['source_URL', 'Readers Choice Votes', 'Readers Choice Category', 'Title', 'Author', 'Total Avg Rating', 'Number of Ratings', 'Number of Reviews', 'Number of Pages', 'Edition', 'Book Description', 'First Published date', 'Kindle Version and Price', 'Kindle Price', 'About the Author']
kindle_cols = ['asin', 'title', 'author', 'soldBy', 'imgUrl', 'productURL', 'stars', 'reviews', 'price', 'isKindleUnlimited', 'category_id', 'isBestSeller', 'isEditorsPick', 'isGoodReadsChoice', 'publishedDate', 'category_name']

def jaro_winkler_matrix(mediated, source):
    sim_matrix = pd.DataFrame(index=mediated, columns=source)

    for m_col in mediated:
        for s_col in source:
            score = jellyfish.jaro_winkler_similarity(m_col.lower(), s_col.lower())
            sim_matrix.loc[m_col, s_col] = score
    return sim_matrix.astype(float)  # Convert to float for better display

# Compute similarity matrices
amazon_sim = jaro_winkler_matrix(mediated_cols, amazon_cols)
goodreads_sim = jaro_winkler_matrix(mediated_cols, goodreads_cols)
kindle_sim = jaro_winkler_matrix(mediated_cols, kindle_cols)

# Display the matrices nicely in Jupyter Notebook
from IPython.display import display

print("Jaro-Winkler similarity with Amazon dataset:")
display(amazon_sim)

print("\nJaro-Winkler similarity with Goodreads dataset:")
display(goodreads_sim)

print("\nJaro-Winkler similarity with Kindle dataset:")
display(kindle_sim)

Jaro-Winkler similarity with Amazon dataset:

,Unnamed: 0,price,ranks,title,no_of_reviews,ratings,author,cover_type,year,genre
title,0.433333,0.600000,0.000000,1.000000,0.425641,0.561905,0.455556,0.366667,0.000000,0.466667
author,0.344444,0.000000,0.455556,0.455556,0.495726,0.539683,1.000000,0.488889,0.611111,0.455556
rating,0.344444,0.577778,0.760000,0.577778,0.414530,0.971429,0.555556,0.511111,0.472222,0.455556
review_count,0.394444,0.627778,0.427778,0.355556,0.382479,0.484127,0.333333,0.588889,0.388889,0.505556
price,0.433333,1.000000,0.466667,0.600000,0.517949,0.561905,0.000000,0.522222,0.000000,0.466667
publication_year,0.441667,0.595833,0.420833,0.484722,0.352564,0.523810,0.555556,0.537500,0.437500,0.000000

Jaro-Winkler similarity with Goodreads dataset:

,source_URL,Readers Choice Votes,Readers Choice Category,Title,Author,Total Avg Rating,Number of Ratings,Number of Reviews,Number of Pages,Edition,Book Description,First Published date,Kindle Version and Price,Kindle Price,About the Author
title,0.433333,0.416667,0.328986,1.000000,0.455556,0.595833,0.419608,0.419608,0.422222,0.561905,0.420833,0.583333,0.575000,0.616667,0.595833
author,0.488889,0.455556,0.446860,0.455556,1.000000,0.555556,0.447712,0.447712,0.455556,0.539683,0.486111,0.538889,0.305556,0.416667,0.581944
rating,0.422222,0.550000,0.543478,0.577778,0.555556,0.451389,0.316993,0.316993,0.322222,0.531746,0.409722,0.438889,0.430556,0.500000,0.486111
review_count,0.572222,0.549206,0.533989,0.355556,0.333333,0.361111,0.436928,0.356209,0.372222,0.634921,0.513889,0.422222,0.482143,0.388889,0.361111
price,0.633333,0.583333,0.574638,0.600000,0.000000,0.000000,0.339216,0.339216,0.344444,0.447619,0.341667,0.583333,0.463889,0.522222,0.420833
publication_year,0.470833,0.387500,0.503120,0.484722,0.555556,0.482143,0.531863,0.520425,0.481944,0.675595,0.560185,0.559722,0.444444,0.578373,0.583333

Jaro-Winkler similarity with Kindle dataset:

,asin,title,author,soldBy,imgUrl,productURL,stars,reviews,price,isKindleUnlimited,category_id,isBestSeller,isEditorsPick,isGoodReadsChoice,publishedDate,category_name
title,0.483333,1.000000,0.455556,0.455556,0.577778,0.433333,0.466667,0.561905,0.600000,0.592157,0.527273,0.544444,0.499145,0.505882,0.499145,0.517949
author,0.472222,0.455556,1.000000,0.000000,0.555556,0.522222,0.588889,0.000000,0.000000,0.408497,0.676768,0.416667,0.576923,0.483660,0.495726,0.658120
rating,0.750000,0.577778,0.555556,0.000000,0.000000,0.511111,0.411111,0.539683,0.577778,0.483660,0.590909,0.333333,0.329060,0.467320,0.414530,0.574786
review_count,0.444444,0.355556,0.333333,0.000000,0.333333,0.494444,0.427778,0.871429,0.627778,0.436928,0.396465,0.388889,0.380342,0.436928,0.493590,0.463675
price,0.483333,0.600000,0.000000,0.000000,0.455556,0.633333,0.000000,0.676190,1.000000,0.505882,0.527273,0.522222,0.517949,0.481046,0.610256,0.499145
publication_year,0.534722,0.484722,0.555556,0.451389,0.451389,0.617262,0.341667,0.401786,0.595833,0.473564,0.548431,0.513889,0.499038,0.464869,0.663462,0.677528

In [77]:
!pip install spacy

Requirement already satisfied: spacy in /opt/anaconda3/lib/python3.12/site-packages (3.7.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (3.0.10)
Requirement already satisfied: thinc<8.3.0,>=8.1.8 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.4.0,>=0.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (0.3.4)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (0.9.4)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (6.4.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (4.67.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (2.11.7)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (25.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (3.5.0)
Requirement already satisfied: numpy>=1.19.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (1.26.4)
Requirement already satisfied: language-data>=1.2 in /opt/anaconda3/lib/python3.12/site-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.14.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.6.15)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /opt/anaconda3/lib/python3.12/site-packages (from thinc<8.3.0,>=8.1.8->spacy) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from thinc<8.3.0,>=8.1.8->spacy) (0.1.5)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /opt/anaconda3/lib/python3.12/site-packages (from typer<0.10.0,>=0.3.0->spacy) (8.2.1)
Requirement already satisfied: cloudpathlib<0.17.0,>=0.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from weasel<0.4.0,>=0.1.0->spacy) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2->spacy) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.2.1)

In [78]:
!python -m spacy download en_core_web_md

Collecting en-core-web-md==3.7.1
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.7.1/en_core_web_md-3.7.1-py3-none-any.whl (42.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 MB 7.8 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: spacy<3.8.0,>=3.7.2 in /opt/anaconda3/lib/python3.12/site-packages (from en-core-web-md==3.7.1) (3.7.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.0.10)
Requirement already satisfied: thinc<8.3.0,>=8.1.8 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.0.10)
Requirement already satisfied: weasel<0.4.0,>=0.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.3.4)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.9.4)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (6.4.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (4.67.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.11.7)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.1.6)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (80.9.0)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (25.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.5.0)
Requirement already satisfied: numpy>=1.19.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.26.4)
Requirement already satisfied: language-data>=1.2 in /opt/anaconda3/lib/python3.12/site-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (4.14.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2025.6.15)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /opt/anaconda3/lib/python3.12/site-packages (from thinc<8.3.0,>=8.1.8->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from thinc<8.3.0,>=8.1.8->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.1.5)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /opt/anaconda3/lib/python3.12/site-packages (from typer<0.10.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (8.2.1)
Requirement already satisfied: cloudpathlib<0.17.0,>=0.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from weasel<0.4.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.2.1)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')

In [79]:
import spacy

# Load a spaCy model with word vectors
nlp = spacy.load("en_core_web_md")  # or "en_core_web_lg" if installed

In [80]:
#Semantic based matching using SpaCy

In [81]:
!python -m spacy download en_core_web_md

Collecting en-core-web-md==3.7.1
  Using cached https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.7.1/en_core_web_md-3.7.1-py3-none-any.whl (42.8 MB)
Requirement already satisfied: spacy<3.8.0,>=3.7.2 in /opt/anaconda3/lib/python3.12/site-packages (from en-core-web-md==3.7.1) (3.7.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.0.10)
Requirement already satisfied: thinc<8.3.0,>=8.1.8 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.0.10)
Requirement already satisfied: weasel<0.4.0,>=0.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.3.4)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.9.4)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (6.4.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (4.67.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.11.7)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.1.6)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (80.9.0)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (25.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.5.0)
Requirement already satisfied: numpy>=1.19.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.26.4)
Requirement already satisfied: language-data>=1.2 in /opt/anaconda3/lib/python3.12/site-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (4.14.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2025.6.15)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /opt/anaconda3/lib/python3.12/site-packages (from thinc<8.3.0,>=8.1.8->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from thinc<8.3.0,>=8.1.8->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.1.5)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /opt/anaconda3/lib/python3.12/site-packages (from typer<0.10.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (8.2.1)
Requirement already satisfied: cloudpathlib<0.17.0,>=0.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from weasel<0.4.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.2.1)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')

In [82]:
import spacy
nlp = spacy.load("en_core_web_md")

In [83]:
def semantic_similarity_matrix(mediated, source):
    sim_matrix = pd.DataFrame(index=mediated, columns=source, dtype=float)

    # Pre-process columns into spaCy docs once
    mediated_docs = {col: nlp(col.replace('_', ' ')) for col in mediated}
    source_docs = {col: nlp(col.replace('_', ' ')) for col in source}

    for m_col, m_doc in mediated_docs.items():
        for s_col, s_doc in source_docs.items():
            sim = m_doc.similarity(s_doc)
            sim_matrix.loc[m_col, s_col] = sim
    return sim_matrix

# Compute semantic similarity matrices
amazon_sem_sim = semantic_similarity_matrix(mediated_cols, amazon_cols)
goodreads_sem_sim = semantic_similarity_matrix(mediated_cols, goodreads_cols)
kindle_sem_sim = semantic_similarity_matrix(mediated_cols, kindle_cols)

print("Semantic similarity with Amazon dataset:")
display(amazon_sem_sim)

print("\nSemantic similarity with Goodreads dataset:")
display(goodreads_sem_sim)

print("\nSemantic similarity with Kindle dataset:")
display(kindle_sem_sim)

Semantic similarity with Amazon dataset:

/var/folders/dy/7r746_5n72x5ql9p02gqf_lm0000gn/T/ipykernel_84955/2164749602.py:10: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  sim = m_doc.similarity(s_doc)

,Unnamed: 0,price,ranks,title,no_of_reviews,ratings,author,cover_type,year,genre
title,0.121587,0.056503,0.281247,1.000000,0.026652,0.143861,0.304554,0.151058,0.188669,0.281920
author,0.112966,-0.042875,0.030829,0.304554,0.120823,0.126354,1.000000,0.145039,0.050737,0.274558
rating,0.250104,0.369809,0.452905,0.163141,0.397799,0.873965,0.161103,0.417571,0.230294,0.166637
review_count,0.127063,0.317446,0.338328,0.182972,0.381543,0.611435,0.254542,0.428896,0.259367,0.150050
price,0.033147,1.000000,0.212818,0.056503,0.156943,0.447789,-0.042875,0.268968,0.166705,0.054848
publication_year,0.100901,0.193210,0.397709,0.286133,0.206299,0.414154,0.300252,0.244725,0.875047,0.169390

Semantic similarity with Goodreads dataset:

,source_URL,Readers Choice Votes,Readers Choice Category,Title,Author,Total Avg Rating,Number of Ratings,Number of Reviews,Number of Pages,Edition,Book Description,First Published date,Kindle Version and Price,Kindle Price,About the Author
title,0.211797,0.173321,0.273025,0.536869,0.163208,0.095180,0.103057,0.097345,0.110816,0.271231,0.253935,0.377515,0.135136,0.056776,0.247149
author,0.226852,0.315466,0.377324,0.180767,0.700956,0.123279,0.198443,0.215921,0.224615,0.342741,0.438337,0.342510,0.313834,0.254491,0.493800
rating,0.271654,0.353040,0.495315,0.215592,0.038584,0.749652,0.558057,0.485194,0.444399,0.407387,0.206410,0.227932,0.499579,0.223520,0.382198
review_count,0.379617,0.416651,0.483417,0.192563,0.042811,0.454524,0.382260,0.376399,0.345077,0.317800,0.233210,0.406932,0.370799,0.208462,0.354420
price,0.180632,0.056621,0.170170,-0.007887,-0.131476,0.257999,0.133840,0.110496,0.085743,0.139428,0.072047,0.157376,0.348122,0.499578,0.021220
publication_year,0.184774,0.215710,0.335578,0.217251,0.123773,0.340468,0.382924,0.351931,0.377920,0.447283,0.251055,0.508138,0.336435,0.082347,0.427785

Semantic similarity with Kindle dataset:

,asin,title,author,soldBy,imgUrl,productURL,stars,reviews,price,isKindleUnlimited,category_id,isBestSeller,isEditorsPick,isGoodReadsChoice,publishedDate,category_name
title,0.007504,1.000000,0.304554,0.0,0.0,0.0,0.159580,0.111179,0.056503,0.0,-0.005247,0.0,0.0,0.0,0.0,0.570984
author,0.018379,0.304554,1.000000,0.0,0.0,0.0,0.159855,0.219019,-0.042875,0.0,-0.047460,0.0,0.0,0.0,0.0,0.299390
rating,0.110833,0.163141,0.161103,0.0,0.0,0.0,0.352412,0.540450,0.369809,0.0,0.105055,0.0,0.0,0.0,0.0,0.298044
review_count,0.084501,0.182972,0.254542,0.0,0.0,0.0,0.209039,0.650324,0.317446,0.0,0.176820,0.0,0.0,0.0,0.0,0.319853
price,0.106587,0.056503,-0.042875,0.0,0.0,0.0,0.071919,0.301991,1.000000,0.0,0.152800,0.0,0.0,0.0,0.0,0.175840
publication_year,0.128144,0.286133,0.300252,0.0,0.0,0.0,0.154922,0.276473,0.193210,0.0,-0.024046,0.0,0.0,0.0,0.0,0.320392

In [84]:
#Instance based Matching using TF-IDF and COSINE SIMILARITY

In [85]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [92]:
def tfidf_cosine_similarity_matrix(mediated, source):
    # Combine all columns (mediated + source) for fitting the vectorizer
    all_cols = mediated + source

    # Vectorize column names using TF-IDF
    vectorizer = TfidfVectorizer(analyzer='word', token_pattern=r'\b\w+\b')
    tfidf_matrix = vectorizer.fit_transform(all_cols)

    # Split vectors into mediated and source parts
    mediated_vecs = tfidf_matrix[:len(mediated)]
    source_vecs = tfidf_matrix[len(mediated):]

    # Compute cosine similarity matrix (mediated x source)
    sim_matrix = cosine_similarity(mediated_vecs, source_vecs)

    # Convert to DataFrame for nice display
    sim_df = pd.DataFrame(sim_matrix, index=mediated, columns=source)
    return sim_df

# Compute similarity matrices
amazon_tfidf_sim = tfidf_cosine_similarity_matrix(mediated_cols, amazon_cols)
goodreads_tfidf_sim = tfidf_cosine_similarity_matrix(mediated_cols, goodreads_cols)
kindle_tfidf_sim = tfidf_cosine_similarity_matrix(mediated_cols, kindle_cols)

print("TF-IDF Cosine similarity with Amazon dataset:")
display(amazon_tfidf_sim)

print("\nTF-IDF Cosine similarity with Goodreads dataset:")
display(goodreads_tfidf_sim)

print("\nTF-IDF Cosine similarity with Kindle dataset:")
display(kindle_tfidf_sim)

TF-IDF Cosine similarity with Amazon dataset:

,Unnamed: 0,price,ranks,title,no_of_reviews,ratings,author,cover_type,year,genre
title,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
author,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
rating,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
review_count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
price,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
publication_year,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

TF-IDF Cosine similarity with Goodreads dataset:

,source_URL,Readers Choice Votes,Readers Choice Category,Title,Author,Total Avg Rating,Number of Ratings,Number of Reviews,Number of Pages,Edition,Book Description,First Published date,Kindle Version and Price,Kindle Price,About the Author
title,0.0,0.0,0.0,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
author,0.0,0.0,0.0,0.0,1.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.490501
rating,0.0,0.0,0.0,0.0,0.0,0.528612,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
review_count,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
price,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.431112,0.670547,0.000000
publication_year,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000

TF-IDF Cosine similarity with Kindle dataset:

,asin,title,author,soldBy,imgUrl,productURL,stars,reviews,price,isKindleUnlimited,category_id,isBestSeller,isEditorsPick,isGoodReadsChoice,publishedDate,category_name
title,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
author,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
rating,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
review_count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
price,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
publication_year,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [94]:
!pip install numpy

Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.12/site-packages (1.26.4)

In [95]:
!pip install numpy

Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.12/site-packages (1.26.4)

In [98]:
#Combining similarity matrices using MIN, MAX, AVG and WEIGHTER AVERAGE

In [100]:
import numpy as np

def generate_combiners(sim_matrices, weights=None):

    index = sim_matrices[0].index
    columns = sim_matrices[0].columns
    matrix_stack = np.array([df.values for df in sim_matrices])

    combined = {
        'min': pd.DataFrame(np.min(matrix_stack, axis=0), index=index, columns=columns),
        'max': pd.DataFrame(np.max(matrix_stack, axis=0), index=index, columns=columns),
        'avg': pd.DataFrame(np.mean(matrix_stack, axis=0), index=index, columns=columns)
    }

    if weights:
        weighted = np.average(matrix_stack, axis=0, weights=np.array(weights))
        combined['weighted_avg'] = pd.DataFrame(weighted, index=index, columns=columns)

    return combined

In [112]:
from IPython.display import display
import numpy as np

# Make sure you already ran this earlier:
# generate_combiners() function

# Define matcher results for each dataset
amazon_matchers = [amazon_sim, amazon_sem_sim, amazon_tfidf_sim]
goodreads_matchers = [goodreads_sim, goodreads_sem_sim, goodreads_tfidf_sim]
kindle_matchers = [kindle_sim, kindle_sem_sim, kindle_tfidf_sim]

# Define weights: Jaro (0.4), Semantic (0.3), TF-IDF (0.3)
weights = [0.4, 0.3, 0.3]

# Generate combined matrices
amazon_combined = generate_combiners(amazon_matchers, weights)
goodreads_combined = generate_combiners(goodreads_matchers, weights)
kindle_combined = generate_combiners(kindle_matchers, weights)

In [307]:
# ----- Amazon Display -----

print(" Amazon - Max Combiner:")
display(amazon_combined['max'])

amazon_combined['max'].to_csv("amazon_max_combiner.csv")

print("Amazon - Weighted Average Combiner:")
display(amazon_combined['weighted_avg'])

amazon_combined['weighted_avg'].to_csv("amazon_weighted_avg_combiner.csv")

 Amazon - Max Combiner:

,Unnamed: 0,price,ranks,title,no_of_reviews,ratings,author,cover_type,year,genre
title,0.433333,0.600000,0.281247,1.000000,0.425641,0.561905,0.455556,0.366667,0.188669,0.466667
author,0.344444,0.000000,0.455556,0.455556,0.495726,0.539683,1.000000,0.488889,0.611111,0.455556
rating,0.344444,0.577778,0.760000,0.577778,0.414530,0.971429,0.555556,0.511111,0.472222,0.455556
review_count,0.394444,0.627778,0.427778,0.355556,0.382479,0.611435,0.333333,0.588889,0.388889,0.505556
price,0.433333,1.000000,0.466667,0.600000,0.517949,0.561905,0.000000,0.522222,0.166705,0.466667
publication_year,0.441667,0.595833,0.420833,0.484722,0.352564,0.523810,0.555556,0.537500,0.875047,0.169390

Amazon - Weighted Average Combiner:

,Unnamed: 0,price,ranks,title,no_of_reviews,ratings,author,cover_type,year,genre
title,0.209809,0.256951,0.084374,1.000000,0.178252,0.267920,0.273588,0.191984,0.056601,0.271243
author,0.171668,-0.012863,0.191471,0.273588,0.234537,0.253779,1.000000,0.239067,0.259666,0.264590
rating,0.212809,0.342054,0.439871,0.280053,0.285152,0.650761,0.270553,0.329716,0.257977,0.232213
review_count,0.195897,0.346345,0.272609,0.197114,0.267454,0.377081,0.209696,0.364224,0.233366,0.247237
price,0.183278,1.000000,0.250512,0.256951,0.254263,0.359099,-0.012863,0.289579,0.050012,0.203121
publication_year,0.206937,0.296296,0.287646,0.279729,0.202915,0.333770,0.312298,0.288417,0.437514,0.050817

In [240]:
# ----- Goodreads Display  -----

print("Goodreads - Max Combiner:")
display(goodreads_combined['max'])
goodreads_combined['max'].to_csv("goodreads_max_combiner.csv")

print(" Goodreads - Weighted Average Combiner:")
display(goodreads_combined['weighted_avg'])
goodreads_combined['weighted_avg'].to_csv("goodreads_weighted_combiner.csv")

Goodreads - Max Combiner:

,source_URL,Readers Choice Votes,Readers Choice Category,Title,Author,Total Avg Rating,Number of Ratings,Number of Reviews,Number of Pages,Edition,Book Description,First Published date,Kindle Version and Price,Kindle Price,About the Author
title,0.433333,0.416667,0.328986,1.000000,0.455556,0.595833,0.419608,0.419608,0.422222,0.561905,0.420833,0.583333,0.575000,0.616667,0.595833
author,0.488889,0.455556,0.446860,0.455556,1.000000,0.555556,0.447712,0.447712,0.455556,0.539683,0.486111,0.538889,0.313834,0.416667,0.581944
rating,0.422222,0.550000,0.543478,0.577778,0.555556,0.749652,0.558057,0.485194,0.444399,0.531746,0.409722,0.438889,0.499579,0.500000,0.486111
review_count,0.572222,0.549206,0.533989,0.355556,0.333333,0.454524,0.436928,0.376399,0.372222,0.634921,0.513889,0.422222,0.482143,0.388889,0.361111
price,0.633333,0.583333,0.574638,0.600000,0.000000,0.257999,0.339216,0.339216,0.344444,0.447619,0.341667,0.583333,0.463889,0.670547,0.420833
publication_year,0.470833,0.387500,0.503120,0.484722,0.555556,0.482143,0.531863,0.520425,0.481944,0.675595,0.560185,0.559722,0.444444,0.578373,0.583333

 Goodreads - Weighted Average Combiner:

,source_URL,Readers Choice Votes,Readers Choice Category,Title,Author,Total Avg Rating,Number of Ratings,Number of Reviews,Number of Pages,Edition,Book Description,First Published date,Kindle Version and Price,Kindle Price,About the Author
title,0.236872,0.218663,0.213502,0.861061,0.231185,0.266887,0.198760,0.197047,0.202134,0.306131,0.244514,0.346588,0.270541,0.263700,0.312478
author,0.263611,0.276862,0.291941,0.236452,0.910287,0.259206,0.238618,0.243861,0.249607,0.318695,0.325946,0.318308,0.216372,0.243014,0.528068
rating,0.250385,0.325912,0.365986,0.295789,0.233797,0.564035,0.294214,0.272356,0.262209,0.334914,0.225812,0.243935,0.322096,0.267056,0.309104
review_count,0.342774,0.344678,0.358621,0.199991,0.146177,0.280802,0.289449,0.255403,0.252412,0.349308,0.275518,0.290968,0.304097,0.218094,0.250771
price,0.307523,0.250320,0.280906,0.237634,-0.039443,0.077400,0.175838,0.168835,0.163501,0.220876,0.158281,0.280546,0.419326,0.559926,0.174699
publication_year,0.243765,0.219713,0.301921,0.259064,0.259354,0.294998,0.327622,0.313749,0.306154,0.404423,0.299390,0.376330,0.278708,0.256053,0.361669

In [399]:
print(" Kindle - Max Combiner:")
display(kindle_combined['max'])
kindle_combined['max'].to_csv("kindle_max_combiner.csv")

print(" Kindle - Weighted Average Combiner:")
display(kindle_combined['weighted_avg'])
kindle_combined['weighted_avg'].to_csv("kindle_weighted_combiner.csv")

 Kindle - Max Combiner:

,asin,title,author,soldBy,imgUrl,productURL,stars,reviews,price,isKindleUnlimited,category_id,isBestSeller,isEditorsPick,isGoodReadsChoice,publishedDate,category_name
title,0.483333,1.000000,0.455556,0.455556,0.577778,0.433333,0.466667,0.561905,0.600000,0.592157,0.527273,0.544444,0.499145,0.505882,0.499145,0.570984
author,0.472222,0.455556,1.000000,0.000000,0.555556,0.522222,0.588889,0.219019,0.000000,0.408497,0.676768,0.416667,0.576923,0.483660,0.495726,0.658120
rating,0.750000,0.577778,0.555556,0.000000,0.000000,0.511111,0.411111,0.540450,0.577778,0.483660,0.590909,0.333333,0.329060,0.467320,0.414530,0.574786
review_count,0.444444,0.355556,0.333333,0.000000,0.333333,0.494444,0.427778,0.871429,0.627778,0.436928,0.396465,0.388889,0.380342,0.436928,0.493590,0.463675
price,0.483333,0.600000,0.000000,0.000000,0.455556,0.633333,0.071919,0.676190,1.000000,0.505882,0.527273,0.522222,0.517949,0.481046,0.610256,0.499145
publication_year,0.534722,0.484722,0.555556,0.451389,0.451389,0.617262,0.341667,0.401786,0.595833,0.473564,0.548431,0.513889,0.499038,0.464869,0.663462,0.677528

 Kindle - Weighted Average Combiner:

,asin,title,author,soldBy,imgUrl,productURL,stars,reviews,price,isKindleUnlimited,category_id,isBestSeller,isEditorsPick,isGoodReadsChoice,publishedDate,category_name
title,0.195584,1.000000,0.273588,0.182222,0.231111,0.173333,0.234541,0.258116,0.256951,0.236863,0.209335,0.217778,0.199658,0.202353,0.199658,0.378475
author,0.194402,0.273588,1.000000,0.000000,0.222222,0.208889,0.283512,0.065706,-0.012863,0.163399,0.256469,0.166667,0.230769,0.193464,0.198291,0.353065
rating,0.333250,0.280053,0.270553,0.000000,0.000000,0.204444,0.270168,0.378008,0.342054,0.193464,0.267880,0.133333,0.131624,0.186928,0.165812,0.319328
review_count,0.203128,0.197114,0.209696,0.000000,0.133333,0.197778,0.233823,0.543669,0.346345,0.174771,0.211632,0.155556,0.152137,0.174771,0.197436,0.281426
price,0.225309,0.256951,-0.012863,0.000000,0.182222,0.253333,0.021576,0.361074,1.000000,0.202353,0.256749,0.208889,0.207179,0.192418,0.244103,0.252410
publication_year,0.252332,0.279729,0.312298,0.180556,0.180556,0.246905,0.183143,0.243656,0.296296,0.189426,0.212158,0.205556,0.199615,0.185948,0.265385,0.367129

In [ ]:
#Applying THRESHOLD and converting to BINARY

In [146]:
def apply_threshold(df, threshold=0.5):
 return df.where(df >= threshold, other=0)

def binarize_matrix(df, threshold=0.5):
    return (df > threshold).astype(int)

In [305]:
THRESHOLD = 0.5
# 📘 Amazon - Binarized Outputs
print(" Amazon - Max Combiner (Binarized):")
display(binarize_matrix(amazon_combined['max'], threshold=THRESHOLD))

print(" Amazon - Weighted Avg Combiner (Binarized):")
display(binarize_matrix(amazon_combined['weighted_avg'], threshold=THRESHOLD))

 Amazon - Max Combiner (Binarized):

,Unnamed: 0,price,ranks,title,no_of_reviews,ratings,author,cover_type,year,genre
title,0,1,0,1,0,1,0,0,0,0
author,0,0,0,0,0,1,1,0,1,0
rating,0,1,1,1,0,1,1,1,0,0
review_count,0,1,0,0,0,1,0,1,0,1
price,0,1,0,1,1,1,0,1,0,0
publication_year,0,1,0,0,0,1,1,1,1,0

 Amazon - Weighted Avg Combiner (Binarized):

,Unnamed: 0,price,ranks,title,no_of_reviews,ratings,author,cover_type,year,genre
title,0,0,0,1,0,0,0,0,0,0
author,0,0,0,0,0,0,1,0,0,0
rating,0,0,0,0,0,1,0,0,0,0
review_count,0,0,0,0,0,0,0,0,0,0
price,0,1,0,0,0,0,0,0,0,0
publication_year,0,0,0,0,0,0,0,0,0,0

In [192]:
THRESHOLD = 0.5
# 📗 Goodreads - Binarized Outputs

print("Goodreads - Max Combiner (Binarized):")
display(binarize_matrix(goodreads_combined['max'], threshold=THRESHOLD))

print("Goodreads - Weighted Avg Combiner (Binarized):")
display(binarize_matrix(goodreads_combined['weighted_avg'], threshold=THRESHOLD))

Goodreads - Max Combiner (Binarized):

,source_URL,Readers Choice Votes,Readers Choice Category,Title,Author,Total Avg Rating,Number of Ratings,Number of Reviews,Number of Pages,Edition,Book Description,First Published date,Kindle Version and Price,Kindle Price,About the Author
title,0,0,0,1,0,1,0,0,0,1,0,1,1,1,1
author,0,0,0,0,1,1,0,0,0,1,0,1,0,0,1
rating,0,1,1,1,1,1,1,0,0,1,0,0,0,0,0
review_count,1,1,1,0,0,0,0,0,0,1,1,0,0,0,0
price,1,1,1,1,0,0,0,0,0,0,0,1,0,1,0
publication_year,0,0,1,0,1,0,1,1,0,1,1,1,0,1,1

Goodreads - Weighted Avg Combiner (Binarized):

,source_URL,Readers Choice Votes,Readers Choice Category,Title,Author,Total Avg Rating,Number of Ratings,Number of Reviews,Number of Pages,Edition,Book Description,First Published date,Kindle Version and Price,Kindle Price,About the Author
title,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
author,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
rating,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
review_count,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
price,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
publication_year,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [196]:
THRESHOLD = 0.5
#  Kindle - Binarized Outputs
print(" Kindle - Max Combiner (Binarized):")
display(binarize_matrix(kindle_combined['max'], threshold=THRESHOLD))

print("Kindle - Weighted Avg Combiner (Binarized):")
display(binarize_matrix(kindle_combined['weighted_avg'], threshold=THRESHOLD))

 Kindle - Max Combiner (Binarized):

,asin,title,author,soldBy,imgUrl,productURL,stars,reviews,price,isKindleUnlimited,category_id,isBestSeller,isEditorsPick,isGoodReadsChoice,publishedDate,category_name
title,0,1,0,0,1,0,0,1,1,1,1,1,0,1,0,1
author,0,0,1,0,1,1,1,0,0,0,1,0,1,0,0,1
rating,1,1,1,0,0,1,0,1,1,0,1,0,0,0,0,1
review_count,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
price,0,1,0,0,0,1,0,1,1,1,1,1,1,0,1,0
publication_year,1,0,1,0,0,1,0,0,1,0,1,1,0,0,1,1

Kindle - Weighted Avg Combiner (Binarized):

,asin,title,author,soldBy,imgUrl,productURL,stars,reviews,price,isKindleUnlimited,category_id,isBestSeller,isEditorsPick,isGoodReadsChoice,publishedDate,category_name
title,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
author,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
rating,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
review_count,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
price,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
publication_year,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [333]:
amazon_max_GT = pd.read_csv('/Users/apple/Desktop/SemanticDataIntegration/Implementation/amazon_max_GT.csv')
display(amazon_max_GT)

amazon_weighted_GT = pd.read_csv('/Users/apple/Desktop/SemanticDataIntegration/Implementation/amazon_weighted_avg_GT.csv')
display(amazon_weighted_GT)

,Unnamed: 0,price,ranks,title,no_of_reviews,ratings,author,cover_type,year,genre
title,0,1,0,1,0,1,0,0,0,0
author,0,0,0,0,0,1,1,0,1,0
rating,0,1,1,1,0,1,1,1,0,0
review_count,0,1,0,0,0,1,0,1,0,1
price,0,1,0,1,1,1,0,1,0,0
publication_year,0,1,0,0,0,1,1,0,1,0

,Unnamed: 0,price,ranks,title,no_of_reviews,ratings,author,cover_type,year,genre
title,0,0,0,1,0,0,0,0,0,0
author,0,0,0,0,0,0,1,0,0,0
rating,0,0,0,0,0,1,0,0,0,0
review_count,0,0,0,0,0,0,0,0,0,0
price,0,1,0,0,0,0,0,0,0,0
publication_year,0,0,0,0,0,0,0,0,0,0

In [335]:
amazon_max_GT.shape

(6, 10)

In [341]:
amazon_weighted_GT.shape

(6, 10)

In [363]:
binarize_matrix(amazon_combined['weighted_avg']).shape

(6, 10)

In [361]:
binarize_matrix(amazon_combined['max']).shape

(6, 10)

In [429]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Binarized predictions (already done earlier)
binarized_max = binarize_matrix(amazon_combined['max'], threshold=THRESHOLD)
binarized_weighted = binarize_matrix(amazon_combined['weighted_avg'], threshold=THRESHOLD)

# Flatten predictions and ground truths
y_true_max = amazon_max_GT.values.flatten()
y_pred_max = binarized_max.values.flatten()

y_true_weighted = amazon_weighted_GT.values.flatten()
y_pred_weighted = binarized_weighted.values.flatten()

# --- Max Combiner Scores ---
precision_max = precision_score(y_true_max, y_pred_max)
recall_max = recall_score(y_true_max, y_pred_max)
f1_max = f1_score(y_true_max, y_pred_max)

# --- Weighted Avg Combiner Scores ---
precision_weighted = precision_score(y_true_weighted, y_pred_weighted)
recall_weighted = recall_score(y_true_weighted, y_pred_weighted)
f1_weighted = f1_score(y_true_weighted, y_pred_weighted)

# --- Display results ---
print("Amazon Dataset")
print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.5 Threshold ")

print(f"Precision: {precision_max:.4f}")
print(f"Recall:    {recall_max:.4f}")
print(f"F1 Score:  {f1_max:.4f}")

print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.5 Threshold ")

print(f"Precision: {precision_weighted:.4f}")
print(f"Recall:    {recall_weighted:.4f}")
print(f"F1 Score:  {f1_weighted:.4f}")

Amazon Dataset
Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.5 Threshold
Precision: 0.9615
Recall:    1.0000
F1 Score:  0.9804
Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.5 Threshold
Precision: 1.0000
Recall:    1.0000
F1 Score:  1.0000

In [431]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Binarized predictions (already done earlier)
binarized_max = binarize_matrix(amazon_combined['max'], threshold=0.6)
binarized_weighted = binarize_matrix(amazon_combined['weighted_avg'], threshold=0.6)

# Flatten predictions and ground truths
y_true_max = amazon_max_GT.values.flatten()
y_pred_max = binarized_max.values.flatten()

y_true_weighted = amazon_weighted_GT.values.flatten()
y_pred_weighted = binarized_weighted.values.flatten()

# --- Max Combiner Scores ---
precision_max = precision_score(y_true_max, y_pred_max)
recall_max = recall_score(y_true_max, y_pred_max)
f1_max = f1_score(y_true_max, y_pred_max)

# --- Weighted Avg Combiner Scores ---
precision_weighted = precision_score(y_true_weighted, y_pred_weighted)
recall_weighted = recall_score(y_true_weighted, y_pred_weighted)
f1_weighted = f1_score(y_true_weighted, y_pred_weighted)

# --- Display results ---
print("Amazon Dataset")
print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.6 Threshold ")

print(f"Precision: {precision_max:.4f}")
print(f"Recall:    {recall_max:.4f}")
print(f"F1 Score:  {f1_max:.4f}")

print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.6 Threshold ")
print(f"Precision: {precision_weighted:.4f}")
print(f"Recall:    {recall_weighted:.4f}")
print(f"F1 Score:  {f1_weighted:.4f}")

Amazon Dataset
Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.6 Threshold
Precision: 1.0000
Recall:    0.3600
F1 Score:  0.5294
Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.6 Threshold
Precision: 1.0000
Recall:    1.0000
F1 Score:  1.0000

In [433]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Binarized predictions (already done earlier)
binarized_max = binarize_matrix(amazon_combined['max'], threshold=0.7)
binarized_weighted = binarize_matrix(amazon_combined['weighted_avg'], threshold=0.7)

# Flatten predictions and ground truths
y_true_max = amazon_max_GT.values.flatten()
y_pred_max = binarized_max.values.flatten()

y_true_weighted = amazon_weighted_GT.values.flatten()
y_pred_weighted = binarized_weighted.values.flatten()

# --- Max Combiner Scores ---
precision_max = precision_score(y_true_max, y_pred_max)
recall_max = recall_score(y_true_max, y_pred_max)
f1_max = f1_score(y_true_max, y_pred_max)

# --- Weighted Avg Combiner Scores ---
precision_weighted = precision_score(y_true_weighted, y_pred_weighted)
recall_weighted = recall_score(y_true_weighted, y_pred_weighted)
f1_weighted = f1_score(y_true_weighted, y_pred_weighted)

# --- Display results --
print("Amazon Dataset")
print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.7 Threshold ")

print(f"Precision: {precision_max:.4f}")
print(f"Recall:    {recall_max:.4f}")
print(f"F1 Score:  {f1_max:.4f}")

print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.7 Threshold ")

print(f"Precision: {precision_weighted:.4f}")
print(f"Recall:    {recall_weighted:.4f}")
print(f"F1 Score:  {f1_weighted:.4f}")

Amazon Dataset
Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.7 Threshold
Precision: 1.0000
Recall:    0.2400
F1 Score:  0.3871
Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.7 Threshold
Precision: 1.0000
Recall:    0.7500
F1 Score:  0.8571

In [439]:
kindle_max_GT = pd.read_csv('/Users/apple/Desktop/SemanticDataIntegration/Implementation/kindle_max_GT.csv')
display(kindle_max_GT)

kindle_weighted_GT = pd.read_csv('/Users/apple/Desktop/SemanticDataIntegration/Implementation/kindle_weighted_GT.csv')
display(kindle_weighted_GT)

,asin,title,author,soldBy,imgUrl,productURL,stars,reviews,price,isKindleUnlimited,category_id,isBestSeller,isEditorsPick,isGoodReadsChoice,publishedDate,category_name
title,0,1,0,0,1,0,0,1,1,1,1,1,0,0,0,1
author,0,0,1,0,1,1,1,0,0,0,1,0,1,0,0,1
rating,1,1,1,0,0,1,0,1,1,0,1,0,0,0,0,1
review_count,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
price,0,1,0,0,0,1,0,1,1,0,1,1,1,1,1,0
publication_year,1,0,1,0,0,1,0,0,1,0,1,1,0,0,1,1

,asin,title,author,soldBy,imgUrl,productURL,stars,reviews,price,isKindleUnlimited,category_id,isBestSeller,isEditorsPick,isGoodReadsChoice,publishedDate,category_name
title,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
author,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
rating,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
review_count,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
price,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
publication_year,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [441]:
binarize_matrix(kindle_combined['max']).shape

(6, 16)

In [443]:
kindle_max_GT.shape

(6, 16)

In [445]:
binarize_matrix(kindle_combined['weighted_avg']).shape

(6, 16)

In [447]:
kindle_weighted_GT.shape

(6, 16)

In [449]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Binarized predictions (already done earlier)
binarized_max = binarize_matrix(kindle_combined['max'], threshold=THRESHOLD)
binarized_weighted = binarize_matrix(kindle_combined['weighted_avg'], threshold=THRESHOLD)

# Flatten predictions and ground truths
y_true_max = kindle_max_GT.values.flatten()
y_pred_max = binarized_max.values.flatten()

y_true_weighted = kindle_weighted_GT.values.flatten()
y_pred_weighted = binarized_weighted.values.flatten()

# --- Max Combiner Scores ---
precision_max = precision_score(y_true_max, y_pred_max)
recall_max = recall_score(y_true_max, y_pred_max)
f1_max = f1_score(y_true_max, y_pred_max)

# --- Weighted Avg Combiner Scores ---
precision_weighted = precision_score(y_true_weighted, y_pred_weighted)
recall_weighted = recall_score(y_true_weighted, y_pred_weighted)
f1_weighted = f1_score(y_true_weighted, y_pred_weighted)

# --- Display results ---
print("Kindle Dataset")
print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.5 Threshold ")

print(f"Precision: {precision_max:.4f}")
print(f"Recall:    {recall_max:.4f}")
print(f"F1 Score:  {f1_max:.4f}")

print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.5 Threshold ")

print(f"Precision: {precision_weighted:.4f}")
print(f"Recall:    {recall_weighted:.4f}")
print(f"F1 Score:  {f1_weighted:.4f}")

Kindle Dataset
Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.5 Threshold
Precision: 0.9302
Recall:    0.9756
F1 Score:  0.9524
Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.5 Threshold
Precision: 1.0000
Recall:    1.0000
F1 Score:  1.0000

In [453]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Binarized predictions (already done earlier)
binarized_max = binarize_matrix(kindle_combined['max'], threshold=0.6)
binarized_weighted = binarize_matrix(kindle_combined['weighted_avg'], threshold=0.6)

# Flatten predictions and ground truths
y_true_max = kindle_max_GT.values.flatten()
y_pred_max = binarized_max.values.flatten()

y_true_weighted = kindle_weighted_GT.values.flatten()
y_pred_weighted = binarized_weighted.values.flatten()

# --- Max Combiner Scores ---
precision_max = precision_score(y_true_max, y_pred_max)
recall_max = recall_score(y_true_max, y_pred_max)
f1_max = f1_score(y_true_max, y_pred_max)

# --- Weighted Avg Combiner Scores ---
precision_weighted = precision_score(y_true_weighted, y_pred_weighted)
recall_weighted = recall_score(y_true_weighted, y_pred_weighted)
f1_weighted = f1_score(y_true_weighted, y_pred_weighted)

# --- Display results ---
print("Kindle Dataset")
print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.6 Threshold ")

print(f"Precision: {precision_max:.4f}")
print(f"Recall:    {recall_max:.4f}")
print(f"F1 Score:  {f1_max:.4f}")

print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.6 Threshold ")
print(f"Precision: {precision_weighted:.4f}")
print(f"Recall:    {recall_weighted:.4f}")
print(f"F1 Score:  {f1_weighted:.4f}")

Kindle Dataset
Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.6 Threshold
Precision: 0.9286
Recall:    0.3171
F1 Score:  0.4727
Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.6 Threshold
Precision: 1.0000
Recall:    0.7500
F1 Score:  0.8571

In [457]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Binarized predictions (already done earlier)
binarized_max = binarize_matrix(kindle_combined['max'], threshold=0.7)
binarized_weighted = binarize_matrix(kindle_combined['weighted_avg'], threshold=0.7)

# Flatten predictions and ground truths
y_true_max = kindle_max_GT.values.flatten()
y_pred_max = binarized_max.values.flatten()

y_true_weighted = kindle_weighted_GT.values.flatten()
y_pred_weighted = binarized_weighted.values.flatten()

# --- Max Combiner Scores ---
precision_max = precision_score(y_true_max, y_pred_max)
recall_max = recall_score(y_true_max, y_pred_max)
f1_max = f1_score(y_true_max, y_pred_max)

# --- Weighted Avg Combiner Scores ---
precision_weighted = precision_score(y_true_weighted, y_pred_weighted)
recall_weighted = recall_score(y_true_weighted, y_pred_weighted)
f1_weighted = f1_score(y_true_weighted, y_pred_weighted)

# --- Display results --
print("Kindle Dataset")
print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.7 Threshold ")

print(f"Precision: {precision_max:.4f}")
print(f"Recall:    {recall_max:.4f}")
print(f"F1 Score:  {f1_max:.4f}")

print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.7 Threshold ")

print(f"Precision: {precision_weighted:.4f}")
print(f"Recall:    {recall_weighted:.4f}")
print(f"F1 Score:  {f1_weighted:.4f}")

Kindle Dataset
Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.7 Threshold
Precision: 1.0000
Recall:    0.1220
F1 Score:  0.2174
Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.7 Threshold
Precision: 1.0000
Recall:    0.7500
F1 Score:  0.8571

In [469]:
goodreads_max_GT = pd.read_csv('/Users/apple/Desktop/SemanticDataIntegration/Implementation/goodreads_max_GT.csv',index_col=0)
display(goodreads_max_GT)

goodreads_weighted_GT = pd.read_csv('/Users/apple/Desktop/SemanticDataIntegration/Implementation/goodreads_w.avg_GT.csv', index_col=0)
display(goodreads_weighted_GT)

,source_URL,Readers Choice Votes,Readers Choice Category,Title,Author,Total Avg Rating,Number of Ratings,Number of Reviews,Number of Pages,Edition,Book Description,First Published date,Kindle Version and Price,Kindle Price,About the Author
title,0,0,0,1,0,1,0,0,0,1,0,1,1,1,1
author,0,0,0,0,1,1,0,0,0,1,0,1,0,0,1
rating,0,1,1,1,1,1,1,0,0,1,0,0,0,0,0
review_count,1,1,1,0,0,0,0,0,0,1,1,0,0,0,0
price,1,1,1,1,0,0,0,0,0,0,0,1,0,1,0
publication_year,0,0,1,0,1,0,1,1,0,1,1,1,0,1,1

,source_URL,Readers Choice Votes,Readers Choice Category,Title,Author,Total Avg Rating,Number of Ratings,Number of Reviews,Number of Pages,Edition,Book Description,First Published date,Kindle Version and Price,Kindle Price,About the Author
title,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
author,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
rating,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
review_count,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
price,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
publication_year,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [471]:
binarize_matrix(goodreads_combined['max']).shape

(6, 15)

In [473]:
goodreads_max_GT.shape

(6, 15)

In [475]:
binarize_matrix(goodreads_combined['weighted_avg']).shape

(6, 15)

In [477]:
goodreads_weighted_GT.shape

(6, 15)

In [481]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Binarized predictions (already done earlier)
binarized_max = binarize_matrix(goodreads_combined['max'], threshold=THRESHOLD)
binarized_weighted = binarize_matrix(goodreads_combined['weighted_avg'], threshold=THRESHOLD)

# Flatten predictions and ground truths
y_true_max = goodreads_max_GT.values.flatten()
y_pred_max = binarized_max.values.flatten()

y_true_weighted = goodreads_weighted_GT.values.flatten()
y_pred_weighted = binarized_weighted.values.flatten()

# --- Max Combiner Scores ---
precision_max = precision_score(y_true_max, y_pred_max)
recall_max = recall_score(y_true_max, y_pred_max)
f1_max = f1_score(y_true_max, y_pred_max)

# --- Weighted Avg Combiner Scores ---
precision_weighted = precision_score(y_true_weighted, y_pred_weighted)
recall_weighted = recall_score(y_true_weighted, y_pred_weighted)
f1_weighted = f1_score(y_true_weighted, y_pred_weighted)

# --- Display results ---
print("Goodreads Dataset")
print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.5 Threshold ")

print(f"Precision: {precision_max:.4f}")
print(f"Recall:    {recall_max:.4f}")
print(f"F1 Score:  {f1_max:.4f}")

print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.5 Threshold ")

print(f"Precision: {precision_weighted:.4f}")
print(f"Recall:    {recall_weighted:.4f}")
print(f"F1 Score:  {f1_weighted:.4f}")

Goodreads Dataset
Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.5 Threshold
Precision: 1.0000
Recall:    1.0000
F1 Score:  1.0000
Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.5 Threshold
Precision: 1.0000
Recall:    1.0000
F1 Score:  1.0000

In [483]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Binarized predictions (already done earlier)
binarized_max = binarize_matrix(goodreads_combined['max'], threshold=0.6)
binarized_weighted = binarize_matrix(goodreads_combined['weighted_avg'], threshold=0.6)

# Flatten predictions and ground truths
y_true_max = goodreads_max_GT.values.flatten()
y_pred_max = binarized_max.values.flatten()

y_true_weighted = goodreads_weighted_GT.values.flatten()
y_pred_weighted = binarized_weighted.values.flatten()

# --- Max Combiner Scores ---
precision_max = precision_score(y_true_max, y_pred_max)
recall_max = recall_score(y_true_max, y_pred_max)
f1_max = f1_score(y_true_max, y_pred_max)

# --- Weighted Avg Combiner Scores ---
precision_weighted = precision_score(y_true_weighted, y_pred_weighted)
recall_weighted = recall_score(y_true_weighted, y_pred_weighted)
f1_weighted = f1_score(y_true_weighted, y_pred_weighted)

# --- Display results ---
print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.6 Threshold ")

print("Amazon Max Combiner:")
print(f"Precision: {precision_max:.4f}")
print(f"Recall:    {recall_max:.4f}")
print(f"F1 Score:  {f1_max:.4f}")

print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.6 Threshold ")
print(f"Precision: {precision_weighted:.4f}")
print(f"Recall:    {recall_weighted:.4f}")
print(f"F1 Score:  {f1_weighted:.4f}")

Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.6 Threshold
Amazon Max Combiner:
Precision: 1.0000
Recall:    0.2051
F1 Score:  0.3404
Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.6 Threshold
Precision: 1.0000
Recall:    0.4000
F1 Score:  0.5714

In [485]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Binarized predictions (already done earlier)
binarized_max = binarize_matrix(goodreads_combined['max'], threshold=0.7)
binarized_weighted = binarize_matrix(goodreads_combined['weighted_avg'], threshold=0.7)

# Flatten predictions and ground truths
y_true_max = goodreads_max_GT.values.flatten()
y_pred_max = binarized_max.values.flatten()

y_true_weighted = goodreads_weighted_GT.values.flatten()
y_pred_weighted = binarized_weighted.values.flatten()

# --- Max Combiner Scores ---
precision_max = precision_score(y_true_max, y_pred_max)
recall_max = recall_score(y_true_max, y_pred_max)
f1_max = f1_score(y_true_max, y_pred_max)

# --- Weighted Avg Combiner Scores ---
precision_weighted = precision_score(y_true_weighted, y_pred_weighted)
recall_weighted = recall_score(y_true_weighted, y_pred_weighted)
f1_weighted = f1_score(y_true_weighted, y_pred_weighted)

# --- Display results --
print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.7 Threshold ")

print(f"Precision: {precision_max:.4f}")
print(f"Recall:    {recall_max:.4f}")
print(f"F1 Score:  {f1_max:.4f}")

print("Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.7 Threshold ")

print(f"Precision: {precision_weighted:.4f}")
print(f"Recall:    {recall_weighted:.4f}")
print(f"F1 Score:  {f1_weighted:.4f}")

Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Max Combiner with 0.7 Threshold
Precision: 1.0000
Recall:    0.0769
F1 Score:  0.1429
Evaluation Scores with Jaro-winkler, spaCy,TF-IDF Cosine Similarity + Weighted_avg Combiner with 0.7 Threshold
Precision: 1.0000
Recall:    0.4000
F1 Score:  0.5714

In [487]:
import pandas as pd

# Load Excel file
df = pd.read_excel('/Users/apple/Desktop/SemanticDataIntegration/Implementation/Evaluation.xlsx') 

# Convert to LaTeX tabular format
latex_table = df.to_latex(index=False)

print(latex_table)

\begin{tabular}{lllrrrr}
\toprule
DATASET & MATCHER & COMBINER & THRESHOLD & PRECISION & RECALL & F1 - SCORE \\
\midrule
Amazon Dataset  & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Max & 0.500000 & 0.960000 & 1.000000 & 0.980000 \\
Amazon Dataset  & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Weighted Average & 0.500000 & 1.000000 & 1.000000 & 1.000000 \\
Amazon Dataset  & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Max & 0.600000 & 1.000000 & 0.360000 & 0.520000 \\
Amazon Dataset  & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Weighted Average & 0.600000 & 1.000000 & 1.000000 & 1.000000 \\
Amazon Dataset  & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Max & 0.700000 & 1.000000 & 0.240000 & 0.380000 \\
Amazon Dataset  & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Weighted Average & 0.700000 & 1.000000 & 0.750000 & 0.850000 \\
NaN & NaN & NaN & NaN & NaN & NaN & NaN \\
Kindle Dataset & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Max & 0.500000 & 0.930000 & 0.970000 & 0.950000 \\
Kindle Dataset & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Weighted Average & 0.500000 & 1.000000 & 1.000000 & 1.000000 \\
Kindle Dataset & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Max & 0.600000 & 0.920000 & 0.370000 & 0.470000 \\
Kindle Dataset & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Weighted Average & 0.600000 & 1.000000 & 0.750000 & 0.850000 \\
Kindle Dataset & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Max & 0.700000 & 1.000000 & 0.120000 & 0.210000 \\
Kindle Dataset & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Weighted Average & 0.700000 & 1.000000 & 0.750000 & 0.850000 \\
NaN & NaN & NaN & NaN & NaN & NaN & NaN \\
GoodReads Dataset & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Max & 0.500000 & 0.670000 & 1.000000 & 0.800000 \\
GoodReads Dataset & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Weighted Average & 0.500000 & 0.830000 & 1.000000 & 0.900000 \\
GoodReads Dataset & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Max & 0.600000 & 0.440000 & 0.300000 & 0.360000 \\
GoodReads Dataset & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Weighted Average & 0.600000 & 1.000000 & 0.600000 & 0.750000 \\
GoodReads Dataset & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Max & 0.700000 & 0.570000 & 0.100000 & 0.170000 \\
GoodReads Dataset & Jaro - winkler, SpaCy, TF-IDF + Cosine Similarity & Weighted Average & 0.700000 & 1.000000 & 0.400000 & 0.570000 \\
\bottomrule
\end{tabular}